In [6]:
import pickle
import numpy as np
import pandas as pd


documents = pickle.load(
    open("../Datasets/FakeNewsNet/dict_documents.pkl", "rb"))
indexes = np.load('../Datasets/FakeNewsNet/indexes.npy')
lbls = np.load('../Datasets/FakeNewsNet/labels.npy')

texts = []
labels = []
for i in range(len(indexes)):
    index = indexes[i]
    texts.append(documents[index])
    if lbls[i] == np.str_("-1"):
        labels.append(0)
    else:
        labels.append(1)

df = pd.DataFrame(data={"text": texts, "label": labels})
df

                                                   text  label
0     When I revealed in this column last year that ...      0
1     Hello, I am rescuing my first puppy next Monda...      0
2     In a new interview with the Hollywood Reporter...      0
3     ES News email The latest headlines in your inb...      0
4     Are Will Truman (Eric McCormack) and Grace Adl...      0
...                                                 ...    ...
6998  Sorry, ladies, Drew Scott is officially off th...      1
6999  Poor Mandy Teefey. If Selena Gomez's mom was h...      1
7000  Lights, camera, “I do!”  Since getting engaged...      1
7001  Image zoom Jesse Grant/Getty Images for NBCUni...      1
7002  UPDATE: This article previously referred to Ka...      1

[7003 rows x 2 columns]

In [7]:
df = df.query("label == 1");
df

                                                   text  label
5298  In The Hollywood Reporter's cover story, the d...      1
5299  Jen Threatens Justin: Stay Away From My Friend...      1
5300  Former Today show host Matt Lauer made at leas...      1
5301  Gigi Hadid has once again spoken out against h...      1
5302  It may be time to finally start mourning Justi...      1
...                                                 ...    ...
6998  Sorry, ladies, Drew Scott is officially off th...      1
6999  Poor Mandy Teefey. If Selena Gomez's mom was h...      1
7000  Lights, camera, “I do!”  Since getting engaged...      1
7001  Image zoom Jesse Grant/Getty Images for NBCUni...      1
7002  UPDATE: This article previously referred to Ka...      1

[1705 rows x 2 columns]

In [8]:
df = df['text'];

df

5298    In The Hollywood Reporter's cover story, the d...
5299    Jen Threatens Justin: Stay Away From My Friend...
5300    Former Today show host Matt Lauer made at leas...
5301    Gigi Hadid has once again spoken out against h...
5302    It may be time to finally start mourning Justi...
                              ...
6998    Sorry, ladies, Drew Scott is officially off th...
6999    Poor Mandy Teefey. If Selena Gomez's mom was h...
7000    Lights, camera, “I do!”  Since getting engaged...
7001    Image zoom Jesse Grant/Getty Images for NBCUni...
7002    UPDATE: This article previously referred to Ka...
Name: text, Length: 1705, dtype: object

In [ ]:
df.to_csv('fake.csv', index=False)